kevinngth/traveller-guide-app

- app/controllers/travellers_controller.rb
- app/models/guide.rb
- app/views/travellers/becomeaguide.html.erb
- config/routes.rb
- db/migrate/20191112012722_add_guide_to_users.rb
- db/schema.rb
when the user clicks become a guide, it changes the boolean of guides in the users table to true
> created a become a guide page 

- app/controllers/guides_controller.rb
- app/controllers/travellers_controller.rb
- app/models/user.rb
- app/views/guides/index.html.erb
created guide dashboard with all of guides details where they can add experiences and see their experiences/requests and reviews
> created guide dashboard

- app/assets/stylesheets/reviews.scss
- app/controllers/reviews_controller.rb
- app/helpers/reviews_helper.rb
- app/models/guide.rb
- app/models/review.rb
- app/models/user.rb
- app/views/reviews/new.html.erb
- config/routes.rb
- db/migrate/20191113034948_create_reviews.rb
- db/schema.rb
- test/controllers/reviews_controller_test.rb
- test/fixtures/reviews.yml
- test/models/review_test.rb
New review page can render, and post
> added crud routes for leave  review

- Gemfile
- Gemfile.lock
- app/channels/room_channel.rb
- app/controllers/conversations_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/travellers_controller.rb
- app/javascript/channels/room_channel.js
- app/javascript/packs/application.js
- app/models/conversation.rb
- app/models/message.rb
- app/views/conversations/index.html.erb
- app/views/layouts/application.html.erb
- app/views/messages/index.html.erb
- app/views/travellers/index.html.erb
- config/routes.rb
- db/migrate/20191113060224_create_conversations.rb
- db/migrate/20191113060326_create_messages.rb
- db/schema.rb
- package.json
- test/channels/room_channel_test.rb
- yarn.lock
Created messenger function and added turbo links back to the messenger instant appear function can work.
> Messenger function

- app/controllers/guides_controller.rb
- app/controllers/travellers_controller.rb
- app/views/guides/index.html.erb
- app/views/guides/show.html.erb
- app/views/messages/index.html.erb
- app/views/travellers/index.html.erb
- db/schema.rb
Guide profile up, and messenger functionality is also working for both travellers and guides
> Guide profile

- app/javascript/channels/room_channel.js
- app/views/messages/index.html.erb
messages display users name, and auto focus on text area everytime message is sent
> messenger stylings

- app/controllers/travellers_controller.rb
- app/javascript/channels/room_channel.js
- app/views/messages/index.html.erb
made some styling changes to the messenger UI
> made some styling changes to the messenger UI

- app/controllers/guides_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/views/guides/index.html.erb
- app/views/reviews/new.html.erb
- app/views/travellers/index.html.erb
- config/routes.rb
traveller can add reviews for guides and it displays on the guides dashboard
> added reviews functionality

- app/controllers/travellers_controller.rb
- app/views/travellers/createsearch.html.erb
- app/views/travellers/findguide.html.erb
- config/routes.rb
Updated search functionality to show all guides if no checkboxes added, changed layout of search results
> Beautify search

- app/controllers/reviews_controller.rb
- app/views/guides/index.html.erb
- app/views/reviews/new.html.erb
- db/migrate/20191114012406_add_rating_to_reviews.rb
- db/schema.rb
New review page has range slider, guides dashboard under reviews section can now see stars based on their rating number. Some formatting changes for the dashboard as well
> users can now give ratings in their reviews

- app/controllers/travellers_controller.rb
- app/views/travellers/_search.html.erb
- app/views/travellers/createsearch.html.erb
- app/views/travellers/findguide.html.erb
- app/views/travellers/persistentresults.html.erb
- config/routes.rb
User's search parameters persist for refreshes. Search result page has search form on side for easy new searches.
> Persistent search results

- app/controllers/application_controller.rb
- app/controllers/guides_controller.rb
- app/controllers/travellers_controller.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/guides/index.html.erb
- app/views/messages/index.html.erb
- app/views/travellers/index.html.erb
- app/views/travellers/profilepic.html.erb
- app/views/users/registrations/edit.html.erb
- config/routes.rb
- db/migrate/20191114044753_create_active_storage_tables.active_storage.rb
- db/schema.rb
users can now go and edit their profile and change their profile picture
> Profile Picture Upload

- app/views/travellers/index.html.erb
- app/views/users/registrations/edit.html.erb
fixed bug where if no picture crashes. Now if no picture blank picture renders stock photo image
> fixed profile pic bugs

- app/javascript/channels/room_channel.js
- app/views/messages/index.html.erb
changed UI for messenger and profile picture uploads
> changed UI for messenger and profile picture uploads

- app/views/shared/_dashboardheader.html.erb
logic for if user does not have a profile pic
> Profilepic

- app/controllers/messages_controller.rb
- app/javascript/channels/room_channel.js
- app/views/messages/index.html.erb
- config/application.rb
changed some UI stylings for the messenger
> changed the messenger UI to look like whatsapp

- app/views/messages/index.html.erb
changed line height for messages
> line height change for the messaging portion

- app/javascript/stylesheets/application.scss
- app/views/guides/index.html.erb
- app/views/travellers/_search.html.erb
- app/views/travellers/persistentresults.html.erb
cosmetic changes to the search page for guides
> styling changes to the guides search page

- app/views/travellers/index.html.erb
…fixed bug where if user is not guide, should not be able to leave a review
> Review Bug

- app/controllers/travellers_controller.rb
- app/views/guides/index.html.erb
- app/views/layouts/application.html.erb
Added guides notifications for guides dashboard
> Guides notifications
